### ISSUE TITLE
Extra headers

### ISSUE THREAD

**Issue by oskbor** [foo-software/lighthouse-check-action#10]
Hi!
Is it possible to specify extra headers when running lighthouse through your action?
There[ seems to be a CLI option](https://github.com/rupesh1/lighthouse/blob/29527a03db3d0c131b0d43fde98ba8b00a242a1b/lighthouse-cli/cli-flags.js#L46) to pass in headers to lighthouse.

Thanks for building and maintaining this action btw! 🎉

**Comment by adamhenson** [comment]
Thanks for opening this @oskbor. It brings up a good point in that we only support a subset of settings. I opened issue #12 so that we can support any settings in the future, but let's go ahead and at least support `extraHeadders` for now. I'm going to help in moving through the PRs from @bjszd.

**Comment by adamhenson** [comment]
Released in [1.0.8](https://github.com/foo-software/lighthouse-check-action/releases/tag/v1.0.8) 🙌
