### ISSUE TITLE
Allow for baseUrl to be defined when testing multiple urls

### ISSUE THREAD

**Issue by pmpinto** [foo-software/lighthouse-check-action#102]
**Is your feature request related to a problem? Please describe.**
Don't think so.

**Describe the solution you'd like**
It would be great, and cleaner too, if we could have a `baseUrl` property where I could define Netlify's preview URL, for instance `https://deploy-preview{{ PR_NUMBER }}--myapp.netlify.app/`.

So that I could have:
```yml
baseUrl: 'https://deploy-preview{{ PR_NUMBER }}--myapp.netlify.app/'
urls: '/one /another /something /else'
```

Instead of:
```yml
urls: 'https://deploy-preview{{ PR_NUMBER }}--myapp.netlify.app/one https://deploy-preview{{ PR_NUMBER }}--myapp.netlify.app/another https://deploy-preview{{ PR_NUMBER }}--myapp.netlify.app/something https://deploy-preview{{ PR_NUMBER }}--myapp.netlify.app/else'
```

**Describe alternatives you've considered**
The one from above.

**Comment by adamhenson** [comment]
Realistically, unfortunately, we won't be supporting this feature request.

**Comment by pmpinto** [comment]
Sad, but understandable.
Thanks 👍

**Comment by adamhenson** [comment]
Sorry, I personally don’t have time. But, certainly feel free to open a PR.
