### ISSUE TITLE
Add major version label for each release

### ISSUE THREAD

**Issue by Tobi-mmt** [foo-software/lighthouse-check-action#110]
**Is your feature request related to a problem? Please describe.**
I want to define the version of the GH action to avoid a major version bump without my interaction. But I also don't want to update the minor and bugfix version manually. They can update autmatically. For that I want to define the GH action in my code like that, just defining the major version:

```yml
 - uses: foo-software/lighthouse-check-action@v9
 ```

Currently this leads to an error because the `v9` tag is not given at all. There are just version tags with the full version like `v9.1.1`.

**Describe the solution you'd like**
For each new release we have to define the detailed version tag and also update the major version tag for this release. Other actions do that curreently, like: https://github.com/actions/setup-node/tags . 
For example we could use the following GH action which manages the version tags automatically: [actions/publish-action](https://github.com/actions/publish-action)

**Describe alternatives you've considered**
Nothing in mind.

**Additional context**
nope

**Comment by adamhenson** [comment]
I disagree with the proposal here. Open source authors should not need to distribute a new major version for every patch or minor version release. The package manager should handle this. For example, Docker and NPM handle this out of the box. The 2 packages you referenced are authored by GitHub, hence they are working around their own limitation.

Sorry, but I will not be doing this to makeup for GitHub's dysfunction. Please open an issue with GitHub Actions.

**Comment by adamhenson** [comment]
Related https://github.com/community/community/discussions/39519#discussioncomment-4185261
