### ISSUE TITLE
**The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)

### ISSUE THREAD

**Issue by ailadas** [foo-software/lighthouse-check-action#114]
**The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)

| Name | Status | Preview | Updated |
| :--- | :----- | :------ | :------ |
| **lighthouse-check-action** | ✅ Ready ([Inspect](https://vercel.com/foo-software/lighthouse-check-action/8kQKqQF1YJhoQmkQY9cugwidwUdF)) | [Visit Preview](https://lighthouse-check-action-git-fix-failing-wor-ba1796-foo-software.vercel.app) | Jul 14, 2022 at 11:55PM (UTC) |

_Originally posted by @vercel[bot] in https://github.com/foo-software/lighthouse-check-action/issues/101#issuecomment-1184923464_

**Comment by adamhenson** [comment]
There is no meaningful content of this issue (are you a robot?) - hence, closing.
