### ISSUE TITLE
Unable to use different threshold values for mobile and desktop device 

### ISSUE THREAD

**Issue by basantPayU** [foo-software/lighthouse-check-action#116]
**Describe the bug**
Failing Workflows by Enforcing Minimum Scores for different devices(mobile and Desktop)

Referring to the docs [here](https://www.foo.software/docs/lighthouse-check-github-action/examples#failing-workflows-by-enforcing-minimum-scores), I am trying to create a job where in I enforce different scores for different devices, currently I don't see a way to do so.

**Comment by adamhenson** [comment]
Hello, this isn’t possible out of the box, however you should be able to create separate jobs for desktop and mobile respectively where you could specify different score failure thresholds.
