### ISSUE TITLE
This github action doesn't read the configFile 

### ISSUE THREAD

**Issue by stixaw** [foo-software/lighthouse-check-action#118]
**Describe the bug**
Here is my Code in the config file:
```module.exports = {
  extends: 'lighthouse:default',
  settings: {
    skipAudits: [
      'is-on-https',
      'redirects-http',
      'uses-http2',
    ],
  },
}
```
here is how I am calling it in the github workflow:
 ```     - name: Generate Lighthouse Report
        uses: foo-software/lighthouse-check-action@v10.0.0
        id: lighthouseCheck
        with:
          configFile: ./lh-config-feature.js
          outputDirectory: ${{ env.LIGHTHOUSE_REPORTS_DIRECTORY }}
          urls: "http://chg-pde-comphealth-feature-${{ env.FEATURE_ID }}.s3-website-us-west-2.amazonaws.com"
```
          

**Expected behavior**
          I should see a report which doesn't show the HTTPS results but it occurs every time in our feature branches.  They are on aws and can't do https.

I looked at the documentation for the lighthouse and for this action and from what I can tell it supports the use of the config file.

**Comment by adamhenson** [comment]
We need to update our documentation, but newer versions of this GitHub Action, this option is called `overridesJsonFile` and an example is [here](https://github.com/foo-software/lighthouse-check-action/blob/master/.github/workflows/overrides.yml).
