### ISSUE TITLE
Does the action utilise google lighthouse ?

### ISSUE THREAD

**Issue by basantPayU** [foo-software/lighthouse-check-action#120]
@adamhenson Could you please confirm if the action utilizes Google Lighthouse

**Comment by adamhenson** [comment]
@basantPayU - The short answer is "yes, of course".

1. The name of this GitHub Action is "Lighthouse Check Action"
2. In the main README, main [link to this GitHub project](https://github.com/foo-software/lighthouse-check-action#lighthouse-check-action) in the first paragraph is the below:
> A GitHub Action for running Lighthouse audits automatically in CI workflows. Lighthouse Check Action provides simple configuration and a long list of features for advanced customization including Slack notifications, AWS S3 HTML report uploads, and more! Check out [the docs](https://www.foo.software/docs/lighthouse-check-github-action/intro) to get started with advanced configurations or refer to the [quick start section below](https://github.com/foo-software/lighthouse-check-action#quick-start).
3. In the about section of this project in the right sidebar:
>GitHub Action for running https://github.com/GoogleChromeLabs Lighthouse audits with all the bells and whistles 🔔 Multiple audits, Slack notifications, and more!
4. This project is open-source and you can find that answer in more detail in the code.

 I am the sole contributor to this project. It is an open-source project in which anyone can view the source code. I volunteer my personal time to extend and maintain this project and answer open "issues" like these. I would appreciate it if in the future you would be more mindful of my time and yours to ask questions that are more thought out and meaningful. Is this really the question you were asking or is there more to it? If there's more to it - then in the future, please elaborate in detail in the issue description. I would really appreciate that. In the meantime feel free to elaborate here on your real question.
