### ISSUE TITLE
Update lighthouse package to the latest version

### ISSUE THREAD

**Issue by RhodesPeter** [foo-software/lighthouse-check-action#126]
**Is your feature request related to a problem? Please describe.**
We are getting different lighthouse scores when running locally on Chrome and via the GitHub action because of a missmatch in lighthouse versions. 

**Describe the solution you'd like**
It would be awesome if the lighthouse version was updated. Current version is 12.0.0 👉 https://www.npmjs.com/package/lighthouse

**Additional context**
We find this package very useful, thanks for building it!

**Comment by frederikkempe** [comment]
Yeah, would love to see the Lighthouse version updated. Thanks in advance!

**Comment by adamhenson** [comment]
Thanks. Yes, we typically upgrade when there are major versions or significant minors and patches. Since Lighthouse 12 was released yesterday, I anticipate we will upgrade within a week. I'll update here when I have one.

**Comment by adamhenson** [comment]
I started the process of upgrading to Lighthouse 12, but identified what seems to be a bug in which "opportunities" are missing. I opened an issue with the Lighthouse project in https://github.com/GoogleChrome/lighthouse/issues/15977

I've decided to hold until this issue has a response and until PageSpeed Insights has adopted Lighthouse 12.

**Comment by frederikkempe** [comment]
@adamhenson Thanks for your update and persistance!

**Comment by adamhenson** [comment]
No problem @frederikkempe - thanks for bearing with me.

**Comment by adamhenson** [comment]
@RhodesPeter @frederikkempe upgrade has been made to use `lighthouse@12.0.0` and we're also matching the major versions of this project now with Lighthouse.

You can now use `foo-software/lighthouse-check-action@v12.0.0` or `foo-software/lighthouse-check-action@latest`.

**Comment by RhodesPeter** [comment]
Thank you!

**Comment by frederikkempe** [comment]
@adamhenson You're a legend!

**Comment by adamhenson** [comment]
No problem, thanks again for bearing with me.
