### ISSUE TITLE
Avoid multiple comments

### ISSUE THREAD

**Issue by schoenwaldnils** [foo-software/lighthouse-check-action#18]
Hi there,

is it possible to update the Github comment instead of multiple comments?
Or maybe skip it when the result is the same? 🤔

**Comment by adamhenson** [comment]
Good question @schoenwaldnils. I've been thinking about this one myself. I'm wondering how other apps / actions handle this. If anyone would like to describe how other apps handle this behavior, that would be great. I'll try to do some research around this topic too when I have time.

**Comment by adamhenson** [comment]
[Codecov would be a good example](https://docs.codecov.io/docs/pull-request-comments#section-behavior) to follow.

**Comment by schoenwaldnils** [comment]
I wrote a script once to push a comment with the link to the deployed PR preview.
There I checked the comment list if my bot already wrote a comment.

https://github.com/schoenwaldnils/blog/blob/master/_infrastructure/commentOnPr.js

Maybe it could be possible to have an identifier and to check if there already is a comment.
And if the result is changed, to update the badges and append the link to the new result 🤔 
Not a small task 😬

**Comment by adamhenson** [comment]
Thanks, yes I don't think this should be too difficult. I think the logic should simply be:
1. Check for existing comment.
2. If a comment exists, delete and post new. The idea being that most people only care about the newest scores on a single PR.

Perhaps an option to keep old comments.

**Comment by adamhenson** [comment]
Addressed in [v1.0.10](https://github.com/foo-software/lighthouse-check-action/releases/tag/v1.0.10) 😎

**Comment by schoenwaldnils** [comment]
It is working that there is only one comment.
But I noticed that there is no indication if there is a change in the comment after new tests/commits.
I'd either add the commit she to the comment or delete the first comment and add a new one.
But the latter might still spam your email or notifications 🤔

**Comment by adamhenson** [comment]
Hey @schoenwaldnils - you can see a history of updates to a comment as [seen here](https://github.com/foo-software/lighthouse-check-action/pull/19#pullrequestreview-395948679)... screenshot below.

<img width="774" alt="Screen Shot 2020-04-20 at 2 06 23 PM" src="https://user-images.githubusercontent.com/747743/79784496-552dc600-8310-11ea-92db-cc6237c7e395.png">

**Comment by schoenwaldnils** [comment]
Ah, I didn't know. Thanks @adamhenson
