### ISSUE TITLE
node_modules

### ISSUE THREAD

**Issue by TatisLois** [foo-software/lighthouse-check-action#32]
Hey!  I was just wondering if it was intentional to push up node_modules to source? I think just the package-lock.json should suffice?

**Comment by adamhenson** [comment]
@TatisLois - unfortunately, this is the default way of creating a GitHub Action. I don't like it either, but [the alternative](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github) adds caveats that cost more than the value.

When we first created this GitHub Action, there wasn't an alternative. I'll be re-evaluating this soon, but it's been on my radar since the beginning so I think it's fair to close this. Feel free to comment further if I didn't answer your question.

**Comment by adamhenson** [comment]
> As an alternative to checking in your node_modules directory you can use a tool called zeit/ncc to compile your code and modules into one file used for distribution.

You have to compile `node_modules` and the source into one massive `dist` file. And you have to have tooling to run the command on every push. I think could be fairly easy automated... just doesn't seem like a better solution 😢

**Comment by adamhenson** [comment]
And just to clarify this is a **JavaScript** GitHub Action. You can also create Docker GitHub Actions which would require checking in `node_modules`.

**Comment by TatisLois** [comment]
> And just to clarify this is a **JavaScript** GitHub Action. You can also create Docker GitHub Actions which wouldn't require checking in `node_modules`.

Thanks for the input, that makes a lot of sense. Would you be open to converting it into Docker GitHub Actions? I have general CI and docker experience but never worked on github actions but would be willing to take it on.

**Comment by adamhenson** [comment]
Thanks for the offer. I too have a lot of Docker and CI experience. No, it's more maintainable for us as a GitHub Action.

**Comment by adamhenson** [comment]
Definitely annoying and surprising that GitHub hasn't provided a better solution. Some related chatter:
- https://github.com/actions/toolkit/issues/100
- https://github.com/actions/hello-world-javascript-action/issues/12
- https://github.com/actions/typescript-action/issues/4

**Comment by 123aswin123** [comment]
@adamhenson Why can't we just do an `npm install` after checkout inside the `main.yml` file, any downsides to it? I can wire it up for you if you want.

**Comment by adamhenson** [comment]
@123aswin123 - This repo provides a GitHub Action. It is not consuming a GitHub Action.

To create a JavaScript action you need to create an action metadata file as [documented here](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action). In this project the action metadata file exists [here](https://github.com/foo-software/lighthouse-check-action/blob/master/action.yml).

[As documented by GitHub](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action#writing-the-action-code), you must commit `node_modules`, with one alternative. There isn't a way around this at this time. This issue isn't relevant to this specific GitHub Action.

```
From your terminal, commit your action.yml, index.js, node_modules, package.json, package-lock.json, and README.md files. If you added a .gitignore file that lists node_modules, you'll need to remove that line to commit the node_modules directory
```

The alternative (which I don't think is the best option for us):

```
As an alternative to checking in your node_modules directory you can use a tool called @vercel/ncc to compile your code and modules into one file used for distribution.
```

This issue and these comments are irrelevant to this project. Please re-direct your comments to GitHub, as this a part of the GitHub Actions API.
