### ISSUE TITLE
feature request: retry logic

### ISSUE THREAD

**Issue by adamhenson** [foo-software/lighthouse-check-action#62]
# Summary

For running Lighthouse locally (not against Foo's API), based on #58 - perhaps we could provide retry logic, allowing the user to specify retry count.

**Comment by adamhenson** [comment]
@Meemaw this feature has been added in [v5.1.0](https://github.com/foo-software/lighthouse-check-action/releases/tag/v5.1.0). `maxRetries` is now also reflected [in the docs](https://www.foo.software/docs/lighthouse-check-github-action/configuration#maxretries).

**Comment by Meemaw** [comment]
Muchas gracias 🙏

**Comment by adamhenson** [comment]
@Meemaw - just a heads up - it seems that this wasn't actually released until just now in [`v5.1.1`](https://github.com/foo-software/lighthouse-check-action/releases/tag/v5.1.1).

In `v5.1.0` the built code wasn't actually released. Unfortunately, with GitHub Actions - we have to commit the built code and NPM modules. This is a manual step that is often overlooked and was so in this case. In the future I'd like to automate this in CI, but that will require an automated build and commit of the built files which could pose risks.
