### ISSUE TITLE
Question - Customise slack notification

### ISSUE THREAD

**Issue by thaiching** [foo-software/lighthouse-check-action#65]
Hi,
   Is it possible to customise the lighthouse metrics data that gets sent to the slack notification rather than using the default slack notification template like this? https://lighthouse-check.s3.amazonaws.com/images/github-actions/github-action-lighthouse-check-slack.png

eg : I would like to include device type and any other extra detailed metrics for each scores in the slack notification. :) Thanks.

**Comment by adamhenson** [comment]
@thaiching - thanks for raising this issue. I don't think we can support customization at this time, however we should reflect the device in Slack messages. I opened and issue in the `lighthouse-check` project where this code change will need to happen. See below:

https://github.com/foo-software/lighthouse-check/issues/56

Closing this as it will be addressed in the linked issue above.

**Comment by adamhenson** [comment]
@thaiching - device type is now included in Slack posts as of [`v5.1.1`](https://github.com/foo-software/lighthouse-check-action/releases/tag/v5.1.1).

Thanks for raising this issue.

**Comment by thaiching** [comment]
Hi Adam,
   Thank you so much for including the device type into the slack notification. :) That's really useful. If I want to run both the desktop and mobile lighthouse audit check for each url by adding the `emulatedFormFactor:all` in the circleci config, I'm getting "all" displayed instead of desktop or mobile for each of the url. 
  
   Is it possible to display either desktop or mobile for each url in this case? Thank you!
   
<img width="792" alt="Untitled" src="https://user-images.githubusercontent.com/7057586/141764696-daeee971-4214-41a6-8bfa-b1cb556d724a.png">

**Comment by adamhenson** [comment]
Hi @thaiching - thanks for reporting… this seems like a valid issue. I should have a fix soon. Re-opening.

**Comment by adamhenson** [comment]
Hi @thaiching - this issue has now been fixed. Feel free to confirm. Closing again,  but let me know if you have further issues

**Comment by thaiching** [comment]
Hi @adamhenson, it's showing both mobile and desktop now. Thank you so much! :)

**Comment by adamhenson** [comment]
Perfect, thanks for confirming!
