### ISSUE TITLE
Error: All URLs failed to be enqueued.

### ISSUE THREAD

**Issue by willpaige** [foo-software/lighthouse-check-action#73]
Hi, this is probably more of a human error. That said, I cannot get it to run as it keeps failing on the above, from what I can see the URL does exist.
![Screenshot 2021-12-13 at 4 23 22 pm](https://user-images.githubusercontent.com/3032885/145849686-ae1ba386-b02f-4657-b0bc-fb56726bb9b0.png)

<img width="552" alt="Screenshot 2021-12-13 at 4 24 25 pm" src="https://user-images.githubusercontent.com/3032885/145849799-5f7f66cd-8515-4c47-b599-e917138ed035.png">

Note: I originally tried with just `url: 'https://www.test.rooster.money/gb/'` but received a similar error. 

Kindly appreciate any help with this! 

Will

**Comment by willpaige** [comment]
Ahh I see, I was following the quick start [https://github.com/foo-software/lighthouse-check-action](here).
![Screenshot 2021-12-13 at 5 07 03 pm](https://user-images.githubusercontent.com/3032885/145858003-c871cd84-e351-47ac-b32b-01d28d4ff32b.png) 

That's worked for me, just need to fix another user setup error now 😄

**Comment by adamhenson** [comment]
Right, ya I know it's confusing. When running this GitHub Action on its own (not against Foo's API), you would use the actual URLs. It will probably make sense in the near future to add a separate, additional field like `pageIds`, so it's not as confusing.
