### ISSUE TITLE
Only include enabled categories in Slack messages

### ISSUE THREAD

**Issue by spencermehta** [foo-software/lighthouse-check-action#81]
**Is your feature request related to a problem? Please describe.**
If I am not tracking certain categories, e.g. `'onlyCategories': ['performance']'`, the Slack update message still includes all 5 categories with the disabled ones just displaying 0.

**Describe the solution you'd like**
Only show entries for enabled categories in the Slack message

**Describe alternatives you've considered**
N/A

**Additional context**
<img width="659" alt="image" src="https://user-images.githubusercontent.com/10732264/154308421-fb801f41-6180-4f35-815a-d0d0370e7f4a.png">

**Comment by adamhenson** [comment]
Thanks for reporting and providing details @spencermehta. I should have a fix for this within a week or sooner.

**Comment by adamhenson** [comment]
@spencermehta this has been addressed and published in [version 8](https://github.com/foo-software/lighthouse-check-action/releases/tag/v8.0.0). Please update your configuration to point at master or version 8 and let me know if you have any issues.

**Comment by spencermehta** [comment]
Works perfectly, thanks!
