### ISSUE TITLE
Multiple runs to generate average scores

### ISSUE THREAD

**Issue by spencermehta** [foo-software/lighthouse-check-action#84]
**Is your feature request related to a problem? Please describe.**
I find that the lighthouse scores vary quite a bit run-to-run, so it's hard to get a consistent feel for the trend of the performance.

**Describe the solution you'd like**
Add an option to run the test `n` times and take an average to be reported in the Slack message.

**Describe alternatives you've considered**
Run lighthouse cli in CI, but this would lose much of the ease of use that this GH Action provides

**Additional context**
N/A

**Comment by adamhenson** [comment]
Hi @spencermehta - thanks for the proposal. I think this is a good idea, however it's one reason I created [www.foo.software](https://www.foo.software).

One source of large inconsistency is the computing resources allocated to the GitHub runners. One solution would be to open an account with Foo and [run on our servers instead](https://www.foo.software/docs/lighthouse-check-github-action/examples#running-on-foo-and-saving-results).

Although I think this is a good idea, it's not a direction I want to take this project (would also add complexity and more failure points)... in favor of using Foo. It's not really an exact solution to the proposal here, but I think it could eliminate the need.
