### ISSUE TITLE
Running the tests behind basic HTTP authentication

### ISSUE THREAD

**Issue by willpaige** [foo-software/lighthouse-check-action#86]
Hi, 

just wondering if there is any way to run the tests with some basic HTTP auth credentials?

Thanks for your time.

Will

**Comment by adamhenson** [comment]
Hello @willpaige - yes, you could use the [`extraHeaders` option](https://www.foo.software/docs/lighthouse-check-github-action/configuration#extraheaders) for [basic authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) or other types of auth (that rely on headers).

```yaml
extraHeaders: '{ "Authorization": "Basic <credentials>" }' 
```

Does that answer your question.

**Comment by willpaige** [comment]
Ahh yes perfect, sorry must've missed that when I skimmed over it. Thanks for your help
