### ISSUE TITLE
GitHub Action device: all should audit mobile and desktop

### ISSUE THREAD

**Issue by billdevcode** [foo-software/lighthouse-check-action#89]
Not sure if this is a bug or new feature, but I think it's a bug since we're following the documentation. Unless there's a way to get both the mobile and desktop audits using the [GitHub Action](https://github.com/marketplace/actions/lighthouse-check) without using `device: 'all'`?

**Describe the bug**

- When using the [GitHub Action approach](https://www.foo.software/docs/lighthouse-check-github-action/intro), the [`device`](https://www.foo.software/docs/lighthouse-check-github-action/configuration#device) configuration does not work expectedly. When using `device: 'all'`, we only get mobile audits.

**To Reproduce**
Provide examples, configurations, etc. Code does not need to be final or exact, but the closer to being exact - the better.

- Setup and use the [GitHub Action](https://github.com/marketplace/actions/lighthouse-check), apply `device: 'all'`, link it to a Slack webhook, and then run the action.

**Expected behavior**

- We should see the mobile and desktop audits on Slack

**Additional context**

- We're using the [Foo account setup](https://www.foo.software/docs/lighthouse-check-github-action/examples#running-on-foo-and-saving-results)

**Comment by adamhenson** [comment]
Thanks for reporting this @billdevcode. This is a bug in the documentation really as the intention was to only support this when not running against Foo's API (only when running on a GitHub Runner). Sorry, the docs were wrong.

I believe we can support this however. I'll take a crack at it most likely tomorrow.

**Comment by adamhenson** [comment]
Hi @billdevcode - this issue is now fixed. Thanks again for reporting. Feel free to confirm or re-open if it doesn't work as you'd expect.
